packages:
  - './packages/auth'
  - './packages/api-explorer'
  - './packages/crud'
  - './packages/data'
  - './packages/resource'
  - './packages/adh'
  - './packages/persona'
  - './packages/adh-registry'
  - './packages/adh-site-config'
  - './packages/adh-site-homes'
  - './packages/adh-api-types'
  - './packages/adh-ui'
  - './packages/deploy-platform'
  - './packages/status-server'
  - './packages/status-web'
  - './packages/next-preflight'
  - './packages/next-headers'
  - './packages/next-env'
  - './packages/adh-next-config'
  - './packages/messaging'
  - './packages/features/*'
