#!/usr/bin/env python3
"""Generate src/help/content.generated.ts from the Markdown files under
src/help/content/.

Each *.md file under the content directory is the single source of truth for
one help/doc topic. This script walks that tree, keys each file by its path
relative to content/ (path separators -> "-", extension stripped), and PRE-
RENDERS each file to sanitised, shiki-highlighted HTML at generation time —
emitting a committed TypeScript module mapping topic key -> HTML string.

Pre-rendering (rather than shipping raw Markdown and rendering at runtime) is
what keeps the Help modal flash-free: the client modal injects finished HTML
directly, with no "Rendering…" pass, and the docs sites inject the same HTML
server-side with no per-build re-processing. There is one derived
representation (HTML), produced once, consumed by every surface.

The Markdown -> HTML conversion is @agenticdevelopertoolkit/markdown's `processMarkdown`
(remark/rehype + shiki + rehype-sanitize) — the SAME pipeline the runtime
renderers use, so the committed HTML is byte-identical to what those would
produce. That pipeline only runs in the JS runtime, so this Python generator
orchestrates (walk files, derive keys, format the module) and invokes `node`
purely as the rendering engine: it pipes {key: markdown} in and reads
{key: html} out. Nothing is reimplemented in Python.

Runnable from anywhere (content dir is resolved relative to this script, not cwd):
  python3 tools/gen-help-content.py            # from packages/web/packages/adh
  python3 packages/web/packages/adh/tools/gen-help-content.py   # from the toolkit root
  python3 tools/gen-help-content.py --check    # assert the committed module is fresh

`--check` is what keeps the committed module honest, and it exists because the module went
stale in exactly the way an unguarded derived artifact does: the MCP catalog gained five
tools (Teams, Persona Knowledge, searchMyData) and the corpus kept advertising 47. The
backend's side of that chain was already pinned (`test/mcp/catalog-snapshot.test.ts` holds
catalog.generated.json against the live registry) — this second hop was not, so the catalog
moved and the help text silently did not. Wired into adh's ci.yml, since that is the job
that has both halves to hand (see the note below).

REQUIRES THE BACKEND'S CATALOG — the one input in this package that comes from outside the
repo. The MCP topic (see MCP_COUNT_PLACEHOLDER below) is filled from
`src/adh/src/mcp/catalog.generated.json` in `agenticdevelopmentstudio/adhbackend`, named to
this script through `ADH_MCP_CATALOG` rather than derived (see `_mcp_catalog_path()`, which
records why the old walk-up cannot work any more). Everything this generator PRODUCES is
committed (`src/help/content.generated.ts`), so a standalone toolkit checkout consumes the
help corpus perfectly well and simply cannot regenerate it: `_mcp_catalog_path()` exits with
that message rather than emitting a module with an unresolved `{{MCP_TOOL_COUNT}}` in it.
Recorded here because it is a real, if narrow, dependency of this repo on a repo it does not
contain — the inverse of the direction the rest of the boundary runs (see
<adh-tools>/sites/scripts/verify_toolkit_boundary.py, which scans import specifiers in
.ts/.tsx/.js and therefore cannot see this file at all).
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

# packages/web/packages/adh/tools -> packages/web/packages/adh
PACKAGE_DIR = Path(__file__).resolve().parent.parent
CONTENT_DIR = PACKAGE_DIR / "src" / "help" / "content"
OUT_PATH = PACKAGE_DIR / "src" / "help" / "content.generated.ts"

# The MCP topic's tool surface is DERIVED, not hand-written: content/mcp/tools.md carries a
# `{{MCP_TOOL_COUNT}}` placeholder and an `<!-- MCP_TOOL_GROUPS -->` marker, and this
# generator fills them from the backend's committed tool-catalog snapshot (produced by
# backend/src/adh/tools/gen-mcp-catalog.py from the real tool registry). So the tool list
# shown in the modal + help/docs can never drift from what the server registers.
MCP_COUNT_PLACEHOLDER = "{{MCP_TOOL_COUNT}}"
MCP_GROUPS_MARKER = re.compile(r"<!--\s*MCP_TOOL_GROUPS\b.*?-->", re.DOTALL)

HEADER = """\
// GENERATED by tools/gen-help-content.py — DO NOT EDIT.
// Run `python3 tools/gen-help-content.py` from packages/web/packages/adh to regenerate.
// Values are PRE-RENDERED HTML (processMarkdown output): sanitised, shiki-highlighted,
// keyed by content-file path (`/`→`-`). Injected as-is by MarkdownHtml — no runtime render.
/* eslint-disable */

export const HELP_CONTENT_HTML: Record<string, string> = {
"""

FOOTER = """\
}
"""

# ESM program run by `node` as the rendering engine. Reads {key: markdown} JSON on
# stdin, runs the shared processMarkdown pipeline on each, writes {key: html} JSON on
# stdout. Resolves @agenticdevelopertoolkit/markdown from PACKAGE_DIR's node_modules (its
# `import` condition -> the built dist), so the package's dist must be present.
NODE_RENDER_PROGRAM = r"""
import { processMarkdown } from '@agenticdevelopertoolkit/markdown'

const chunks = []
for await (const chunk of process.stdin) chunks.push(chunk)
const entries = JSON.parse(Buffer.concat(chunks).toString('utf8'))

const out = {}
for (const [key, markdown] of Object.entries(entries)) {
  const { html } = await processMarkdown(markdown)
  out[key] = html
}

process.stdout.write(JSON.stringify(out))
"""


def topic_key(md_path: Path) -> str:
    """content/oauth/register-app.md -> oauth-register-app"""
    rel = md_path.relative_to(CONTENT_DIR).with_suffix("")
    return "-".join(rel.parts)


def _mcp_catalog_path() -> Path:
    """The backend's committed MCP tool-catalog snapshot, which is an INPUT.

    It used to be a computed path: walk up to the ancestor holding both
    `backend/src/adh` and `frontend/`, i.e. the adh monorepo root. That ancestor
    stopped existing on 2026-08-31, when the backend left for
    `agenticdevelopmentstudio/adhbackend` — no repo in the fleet has both
    directories any more, so the walk can no longer succeed anywhere and the
    fallback would only ever be a slower way to reach the same SystemExit.

    So it is an explicit input now, exactly like `ADH_OPENAPI_SPEC` in this repo's
    adh-api-types package, and for the same reason stated there: this repo is
    consumed standalone by repos that have no catalog at all, and there is no
    relative location it could honestly derive. Every consumer names it: adh's CI
    passes the path from its own workspace, and by hand you name whichever
    checkout holds `src/adh/src/mcp/catalog.generated.json`. Naming no particular
    checkout here is deliberate — the file has already changed repositories once,
    and a docstring that hard-codes where it lives this month is the thing that
    goes quietly wrong next time.
    """
    raw = os.environ.get("ADH_MCP_CATALOG")
    if not raw:
        raise SystemExit(
            "no MCP tool catalog given. This generator reads the backend's committed "
            "snapshot, which does not live in this repo — it is in "
            "agenticdevelopmentstudio/adhbackend. Set ADH_MCP_CATALOG:\n"
            "  ADH_MCP_CATALOG=<adhbackend>/src/adh/src/mcp/catalog.generated.json "
            "python3 tools/gen-help-content.py --check"
        )
    return Path(raw).expanduser().resolve()


def _render_tool_groups(catalog: dict) -> str:
    """Render the catalog's groups as GFM: a `## Title · N tools` heading, the blurb,
    and a `| Tool | Access |` table per group. H2 because the groups sit directly under
    the tools topic's H1 (content/mcp/tools.md)."""
    blocks: list[str] = []
    for group in catalog["groups"]:
        lines = [
            f"## {group['title']} · {group['count']} tools",
            "",
            group["blurb"],
            "",
            "| Tool | Access |",
            "| --- | --- |",
        ]
        for tool in group["tools"]:
            lines.append(f"| `{tool['name']}` | {'Write' if tool['write'] else 'Read'} |")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def inject_mcp_catalog(markdown: str) -> str:
    """For the MCP topic, replace the count placeholder + tool-groups marker with the
    surface derived from the backend catalog snapshot. A no-op for every other topic;
    fails fast if the markers are present but the snapshot isn't (run gen-mcp-catalog.py)."""
    if MCP_COUNT_PLACEHOLDER not in markdown and not MCP_GROUPS_MARKER.search(markdown):
        return markdown

    path = _mcp_catalog_path()
    if not path.exists():
        raise SystemExit(
            f"mcp/tools.md needs the tool catalog but {path} is missing.\n"
            "ADH_MCP_CATALOG named it; check the path, or regenerate it with "
            "`python3 tools/gen-mcp-catalog.py` from adhbackend's src/adh."
        )
    catalog = json.loads(path.read_text(encoding="utf-8"))

    markdown = markdown.replace(MCP_COUNT_PLACEHOLDER, str(catalog["total"]))
    markdown = MCP_GROUPS_MARKER.sub(lambda _m: _render_tool_groups(catalog), markdown)

    if MCP_COUNT_PLACEHOLDER in markdown or MCP_GROUPS_MARKER.search(markdown):
        raise SystemExit("MCP catalog substitution left an unresolved marker in mcp/tools.md")
    return markdown


def render_html(entries: dict[str, str]) -> dict[str, str]:
    """Pre-render {key: markdown} -> {key: html} via node + processMarkdown."""
    result = subprocess.run(
        ["node", "--input-type=module", "-e", NODE_RENDER_PROGRAM],
        input=json.dumps(entries),
        cwd=PACKAGE_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(
            "processMarkdown render failed (is @agenticdevelopertoolkit/markdown built?):\n"
            + result.stderr.strip()
        )
    rendered: dict[str, str] = json.loads(result.stdout)
    missing = set(entries) - set(rendered)
    if missing:
        raise SystemExit(f"renderer dropped topics: {sorted(missing)}")
    return rendered


def render_module() -> tuple[str, int]:
    """The exact bytes content.generated.ts should hold right now, and the topic count."""
    md_files = sorted(CONTENT_DIR.rglob("*.md"))
    if not md_files:
        raise SystemExit(f"no *.md files found under {CONTENT_DIR}")

    entries: dict[str, str] = {}
    for md_path in md_files:
        key = topic_key(md_path)
        if key in entries:
            raise SystemExit(f"duplicate topic key {key!r} from {md_path}")
        entries[key] = inject_mcp_catalog(md_path.read_text(encoding="utf-8"))

    rendered = render_html(entries)

    lines = [HEADER]
    for key in sorted(rendered):
        lines.append(f"  {json.dumps(key)}: {json.dumps(rendered[key])},\n")
    lines.append(FOOTER)
    return "".join(lines), len(rendered)


def check(module: str, topics: int) -> int:
    """Compare the committed module against what this run produces. Returns an exit code.

    Byte comparison rather than a numeric spot-check on purpose: this file is derived from
    TWO inputs — the Markdown corpus and adh's MCP catalog snapshot — and either can move
    without the other. Only a full compare catches both, and it costs one extra read.
    """
    if not OUT_PATH.exists():
        print(f"{OUT_PATH} is missing — run this script without --check", file=sys.stderr)
        return 1
    if OUT_PATH.read_text(encoding="utf-8") == module:
        print(f"ok — {OUT_PATH.name} is fresh ({topics} topics)", file=sys.stderr)
        return 0
    print(
        f"STALE: {OUT_PATH} does not match its sources.\n"
        "  Regenerate with `python3 tools/gen-help-content.py` from packages/web/packages/adh\n"
        "  and commit the result. Causes, in order of likelihood: a *.md file under\n"
        f"  {CONTENT_DIR.name}/ changed, or a tool was added/renamed/removed in adh's MCP\n"
        "  registry (which moves catalog.generated.json, which this module embeds).",
        file=sys.stderr,
    )
    return 1


def main() -> None:
    checking = "--check" in sys.argv[1:]
    module, topics = render_module()
    if checking:
        raise SystemExit(check(module, topics))

    OUT_PATH.write_text(module, encoding="utf-8")
    print(f"wrote {OUT_PATH.name}: {topics} topics (pre-rendered HTML)", file=sys.stderr)


if __name__ == "__main__":
    main()
