import type { ReactNode } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'
import { landingFromData } from '../fromData'

const html = (node: ReactNode) => renderToStaticMarkup(<>{node}</>)

// The shape content-buildr writes: a banner key first, rich values as `$inline` trees, plain ones as
// strings. See content-buildr's `render._data` and `inline_tree.to_tree`.
const DATA = {
  $generated: 'GENERATED by content-buildr from sites/x.md — do not edit.',
  hero: {
    headline: { $inline: ['Agentic Developer ', { t: 'b', c: ['Hub'] }] },
    tagline: 'Plain words.',
    blocks: [],
  },
  sections: [
    {
      id: 'what-it-is',
      eyebrow: 'What it is',
      blocks: [
        {
          kind: 'Lede',
          children: {
            $inline: [
              'The ',
              { t: 'link', href: '/details', c: ['details'] },
              ' and the ',
              { t: 'a', href: 'https://x.example', c: [{ t: 'em', c: ['cookbook'] }] },
              ', with ',
              { t: 'code', c: ['<b>'] },
              '.',
            ],
          },
        },
        { kind: 'Code', text: 'a b\n  c {d}' },
      ],
    },
  ],
  tour: { position: { step: 2, total: 3 }, back: { site: 'hub', label: 'Hub' } },
}

function RouteLink({ href, children }: { href: string; children?: ReactNode }) {
  return (
    <a href={href} data-route="">
      {children}
    </a>
  )
}

describe('landingFromData', () => {
  it('drops the generator’s own keys', () => {
    expect('$generated' in landingFromData(DATA)).toBe(false)
  })

  it('passes a plain value through untouched', () => {
    const out = landingFromData(DATA)
    expect(out.hero.tagline).toBe('Plain words.')
    expect(out.sections[0]!.eyebrow).toBe('What it is')
    expect(out.sections[0]!.blocks[1]).toEqual({ kind: 'Code', text: 'a b\n  c {d}' })
    expect(out.tour).toEqual({ position: { step: 2, total: 3 }, back: { site: 'hub', label: 'Hub' } })
  })

  it('turns a rich value into the markup it names', () => {
    expect(html(landingFromData(DATA).hero.headline)).toBe('Agentic Developer <b>Hub</b>')
  })

  it('renders a route link as the site’s component, and anything else as an anchor', () => {
    const block = landingFromData(DATA, { link: RouteLink }).sections[0]!.blocks[0]
    expect(html((block as { children: ReactNode }).children)).toBe(
      'The <a href="/details" data-route="">details</a> and the ' +
        '<a href="https://x.example"><em>cookbook</em></a>, with <code>&lt;b&gt;</code>.',
    )
  })

  it('renders a route link as a plain anchor when the site names no component', () => {
    const block = landingFromData(DATA).sections[0]!.blocks[0]
    expect(html((block as { children: ReactNode }).children)).toContain(
      '<a href="/details">details</a>',
    )
  })
})
