// GENERATED FILE — do not edit by hand.
// Regenerate: python3 <websites-root>/tools/gen-site-routes.py --region hub
//
// hub's share of the fleet's page routes, derived from that repo's App Router
// trees. The rest is in its siblings `routes.community.generated.ts`, `routes.cookbook.generated.ts`, `routes.devteam.generated.ts`, `routes.docs.generated.ts`, `routes.main.generated.ts`, `routes.marketing.generated.ts`, `routes.personaregistry.generated.ts`, `routes.placeholder.generated.ts`, `routes.registry.generated.ts`, `routes.research.generated.ts`, `routes.shipr.generated.ts`, `routes.toolkit.generated.ts`, written by the other repos;
// `routes.generated.ts` merges them all and is what consumers import. See the
// generator's docstring for why this is one file per repo.
//
// `gen-site-routes.py --region hub --check` re-derives this map in that
// repo's CI, so a page added, moved, or removed anywhere in its fleet fails there
// until the script is re-run.
//
// NOT dev-only tooling: research's `src/lib/sitemap-routes.ts` reads
// `SITE_ROUTES.research` at build time to derive which top-level and
// `[workspace]`-child segments are STATIC — i.e. which author or paper slugs would
// be shadowed by a real route — so research's public sitemap is a second,
// load-bearing consumer of this map, not just the flyout above. Do not prune
// either half for being unused outside dev tooling.
import type { SiteId } from './registry'

export const SITE_ROUTES_HUB: Partial<Record<SiteId, readonly string[]>> = {
  admin: [
    '/',
    '/audit',
    '/auth/callback',
    '/authentication',
    '/feature-flags',
    '/feedback',
    '/invitations',
    '/llm-providers',
    '/login',
    '/messaging',
    '/privacy',
    '/reserved-identifiers',
    '/server-bags',
    '/sync',
    '/terms',
    '/usage',
    '/users',
  ],
  hub: [
    '/',
    '/[workspace]/[[...path]]',
    '/[workspace]/academy/[[...path]]',
    '/[workspace]/all-data/[[...table]]',
    '/[workspace]/applications/[[...path]]',
    '/[workspace]/auth/[[...path]]',
    '/[workspace]/billing/[[...path]]',
    '/[workspace]/codereviews/[[...path]]',
    '/[workspace]/communities/[[...path]]',
    '/[workspace]/community/[[...path]]',
    '/[workspace]/consultants/[[...path]]',
    '/[workspace]/consulting/[[...path]]',
    '/[workspace]/cookbook/[[...path]]',
    '/[workspace]/customers/[[...path]]',
    '/[workspace]/dashboards/[[...path]]',
    '/[workspace]/devices/[[...path]]',
    '/[workspace]/devteam/[[...path]]',
    '/[workspace]/docs/[[...path]]',
    '/[workspace]/domains/[[...path]]',
    '/[workspace]/education/[[...path]]',
    '/[workspace]/email-signup',
    '/[workspace]/feature-flags/[[...path]]',
    '/[workspace]/games/[[...path]]',
    '/[workspace]/gamification/[[...path]]',
    '/[workspace]/help/[[...path]]',
    '/[workspace]/integrations/[[...path]]',
    '/[workspace]/invitations/[[...path]]',
    '/[workspace]/knowledgebases/[[...path]]',
    '/[workspace]/llm-providers/[[...path]]',
    '/[workspace]/members',
    '/[workspace]/messaging/[[...path]]',
    '/[workspace]/narratives/[[...path]]',
    '/[workspace]/news/[[...path]]',
    '/[workspace]/notebook/[[...path]]',
    '/[workspace]/notifications/[[...path]]',
    '/[workspace]/orgs/[[...path]]',
    '/[workspace]/persona-services/[[...path]]',
    '/[workspace]/personabuilder/[[...path]]',
    '/[workspace]/personas/[[...path]]',
    '/[workspace]/products/[[...path]]',
    '/[workspace]/profile',
    '/[workspace]/projects/[[...path]]',
    '/[workspace]/recipes/[[...path]]',
    '/[workspace]/registries/[[...path]]',
    '/[workspace]/registry/[[...path]]',
    '/[workspace]/research/[[...path]]',
    '/[workspace]/server-bags/[[...path]]',
    '/[workspace]/settings/[[...path]]',
    '/[workspace]/shipr/[[...path]]',
    '/[workspace]/signin-apps/[[...path]]',
    '/[workspace]/sites/[[...path]]',
    '/[workspace]/storage/[[...path]]',
    '/[workspace]/store/[[...path]]',
    '/[workspace]/stores/[[...path]]',
    '/[workspace]/support/[[...path]]',
    '/[workspace]/teambuilder/[[...path]]',
    '/[workspace]/teams/[[...path]]',
    '/[workspace]/testing/[[...path]]',
    '/[workspace]/tokens/[[...path]]',
    '/[workspace]/toolkit/[[...path]]',
    '/[workspace]/tools/[[...path]]',
    '/admin/[[...path]]',
    '/auth/callback',
    '/contact',
    '/details',
    '/details/[topic]',
    '/explore',
    '/features/[id]',
    '/home',
    '/integrations/oauth-callback',
    '/join',
    '/join/[eco]',
    '/join/verify',
    '/login',
    '/oidc/login',
    '/old-landing',
    '/privacy',
    '/settings/[[...topic]]',
    '/signup',
    '/terms',
    '/tour',
  ],
  'hub-help': [
    '/',
    '/[...slug]',
    '/auth/callback',
    '/chat',
    '/home',
    '/privacy',
    '/rest-api',
    '/rest-api/[...slug]',
    '/terms',
  ],
  status: [
    '/',
    '/privacy',
    '/terms',
  ],
}
